=== MeMartijn/PurePlainDataset/raw_data/req_document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This document describes the schema for a requirement document in XML format-->
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="req_document.xsd"
xmlns="req_document.xsd">



<!-- definition of simple elements -->
<xs:element name="version" type="xs:string"/>
<xs:element name="issue_date" type="xs:date"/>
<xs:element name="file_number" type="xs:string"/>
<xs:element name="source" type="xs:string"/>

<xs:element name="change_date" type="xs:date"/>

<xs:element name="change" type="xs:string"/>


<xs:element name="modifier" type="xs:string"/>



<xs:element name="text_body" type="structured_content"/>
<xs:element name="crossref" type="xs:string"/>
<xs:element name="description" type="list"/>
<xs:element name="enum" type="list"/>
<xs:element name="itemize" type="list"/>
<xs:element name="item" type="structured_content"/>

<xs:element name="term" type="xs:string"/>

<xs:element name="meaning" type="structured_content"/>



<!-- definition of complex elements -->

<!--a title can be a plain text title or a list of nested titles, which are intended as the sub-titles-->
<xs:element name="title">
	<xs:complexType mixed="true">
		<xs:sequence minOccurs="0">
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="title"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!--p is the paragraph, which can optionally have a title, can have nested paragraphs, 
requirements, plain text  (text_body) and can contain a glossary-->
<xs:element name="p">
	<xs:complexType mixed="false">
		<xs:sequence>
			<xs:element ref="title" minOccurs="0" maxOccurs="1"/>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="p" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="req" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="text_body" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="glossary" minOccurs="0" maxOccurs="1"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
</xs:element>

<!--
chance_log_item is the item for the list of changes in a document (the change_log element)-->
<xs:element name="change_log_item">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="version"  maxOccurs="1"/>
			<xs:element ref="change" maxOccurs="1"/>
			<xs:element ref="change_date" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!--
change_log defines a list of changes to the requirements document in the form of change_log_item(s)-->
<xs:element name="change_log">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="change_log_item" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!--glossary_item is a couple term-meaning used in the glossary, if this is contained in the document-->
<xs:element name="glossary_item">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="term"/>
			<xs:element ref="meaning"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!--
glossary is a list of glossary_item-->
<xs:element name="glossary">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="glossary_item" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>


<xs:element name="req">
	<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element ref="text_body"/>
				<xs:element ref="modifier" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="part" type="xs:string" use="optional"/>
			<xs:attribute name="part_id" type="xs:string" use="optional"/>
	</xs:complexType>
</xs:element>

<!-- req_document is the root tag for the overall document.
a requirement document can have requirements without paragraphs or paragraphs with requirements-->
<xs:element name="req_document">
	<xs:complexType mixed="true">
		<xs:sequence>
			<xs:element ref="title" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="version" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="issue_date" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="file_number" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="source" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="change_log" minOccurs="0" maxOccurs="1"/>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="p"/>
				<xs:element ref="req"/>
			</xs:choice> 
		</xs:sequence>
	</xs:complexType>
</xs:element>


<!-- definition of complex types -->

<!-- a list is a set of items which are structured_content objects-->
<xs:complexType name="list" mixed="false">
	<xs:sequence>
		<xs:element ref="item" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<!-- this type defines a textual structured content which might contain possibly nested item lists, enumerations, etc. -->
<xs:complexType name="structured_content" mixed="true">
	<xs:sequence minOccurs="0">
		<xs:choice maxOccurs="unbounded">
			<xs:element ref="crossref" minOccurs="0"/>
			<xs:element ref="enum" minOccurs="0"/>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="itemize" minOccurs="0"/>
		</xs:choice>
	</xs:sequence>
</xs:complexType>



</xs:schema>

=== MeMartijn/PurePlainDataset/raw_data/0000 - gamma j.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- New document created with EditiX at Tue Jun 07 14:21:44 CEST 2011 -->
<req_document xsi:schemaLocation="req_document.xsd req_document.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="req_document.xsd">

<title>
    <title></title>
    <title>Software Requirements Specification (SRS)</title>
    <title>Gamma-J Connecting Retailers through the World</title>
    <title>Gamma-J</title>
    <title>Gamma-J Web Store</title>
</title>

<version>0.0</version>




<p id="1">
    <title>
    Introduction
    </title>
    <p id="1.1">
        <title>
        Purpose
        </title>
        <text_body>
            This is the Software Requirements Specification for GAMMA-J’s Web Store. This Web Store is designed to allow new online store owners a quick and easy means to setup and perform sales and other core business over the internet. This document will outline all of the functions, capabilities and requirements for Version 1 of GAMMA-J’s Web Store. Version 1 is planned for implementation on a “plug and play” USB Key. Future versions will be based on other network appliances.
        </text_body>
    </p>
    <p id="1.2">
        <title>
        Document Conventions
        </title>
        <text_body>
        None
        </text_body>
    </p>
    <p id="1.3">
        <title>
        Intended Audience, Reading Suggestions
        </title>
        <text_body>
            This document is intended to flush out the requirements by the customer GAMMA-J. The customer can review this document to ensure their needs along with the needs of their user’s are being met in their new Web Store program. The development team will also use this document for guidance on overall design and implementation of the Web Store system. The test and verification team can reference this to ensure the requirements are being meet for the customer. Finally, the tech writer will use this to assist with user documentation. This document is designed to be review from beginning to end; however, readers who are new to technical documentation may want to refer to Appendix E: Data Dictionary first.
        </text_body>
    </p>
    <p id="1.4">
        <title>
            Project Scope
        </title>
        <text_body>
            According to GAMMA-J’s Functional Needs Statement this Web Store will:
            <itemize>
                <item>Manage customer accounts</item>
                <item>Manage an online store inventory</item>
                <item>Confirm Orders</item>
                <item>Have an unambiguous interface to assist in browsing the categories and products</item>
                <item>Use Secure Socket Layer (SSL) for security</item>
                <item>Have an availability of 99.999&#37;</item>
                <item>Allow an optional mirror site for reliability and backups</item>
                <item>Feature interface for future software enhancement via “Plug-ins”</item>
                <item></item>
                <item></item>
                <item></item>
                <item></item>
                <item></item>
            </itemize>
            The initial inventory will be 100 items. Expandable with unique codes, the owners can purchase to expand the inventory. The minimum total inventory will be 20,000 items. Since this will be a “Plug and Play device”, no software installation will be necessary. This software will contain all of the basic needs to manage an online store. Advanced needs can be added in the future via “plug-ins.” More detail on the functionality of the Web Store can be found in part 3. System Features and in the function Needs statement.
        </text_body>
    </p>
    <p id="1.5">
        <title>
        References
        </title>
        <text_body>
        This document draws insight from the Web Store System Overview, Functional Needs Statement, and Stakeholder Goals List.
        </text_body>
    </p>
</p>

<p id="2">
    <title>
    Overall Description
    </title>
    <p id="2.1">
        <title>
        Product Perspective
        </title>
        <text_body>
            Web Store is a new system designed for users new to the online E-commerce. This will be a plug and play device with its own CPU and operating system. The Web Store will be a quick and easy means to setup and operate an online Web Store. The Figure 2.1 is a context diagram showing external system interfaces.
        </text_body>
    </p>
    <p id="2.2">
        <title>
        Product Features
        </title>
        <text_body>
            <description>
            <item>Account Management (AM) (High Priority): AM allows users to create, edit, and view accounts information. It also allows the user to login/out of the system.</item>
            <item>Search Engine (SE) (Medium Priority): SE is the tool that assists the user in finding a specific item in the database. It can receive search criteria, find search criteria, and return the results of the search.</item>
            <item>Product Management (PM) (High Priority): PM allows sales personnel to manage the product line shown on the web site.</item>
            <item>Shopping Cart (SC) (Medium Priority): SC is temporary storage for customers shopping on the web. Items from the inventory can be reserved in a virtual cart until the customer decides to purchase them.</item>
            <item>Purchasing and Payment (PP) (High Priority): PP is used to approve and transfer payment from buyers when purchasing items in the cart.</item>
            </description>
        </text_body>
    </p>
    <p id="2.3">
        <title>
        User Classes
        </title>
        <text_body>
            <description>
            <item>System Administrator: Is generally the owner that takes care of maintenance for the Web Store system. The administrator will be in charge of assigning privileges of accounts. Suggested more than one individual can have administrator privilege to ensure advisability. Full documentation will be provided to the Administrator to assist with this process.</item>
            <item>Sales Personnel: Is generally the owner of the Web Store tasked with updating inventory and product line descriptions. Once added, sales personnel can add, delete and change descriptions, pictures, prices, and when ready flag items for customers to buy.</item>
            <item>Customer: A customer is an individual wishing to purchase inventory from GAMMA-J’s Web Store. The Web store will have a variety of clientele depending upon the inventory loaded on the Key. When creating a new account on Web Store it will default as a customer account. Later if the account needs to be upgraded the administrator can accomplish this via the administrator interface.</item>
            </description>
        </text_body>
    </p>
    <p id="2.4">
        <title>
        Operating Environment
        </title>
        <req id="OE-1">
            <text_body>
            Web Store shall operate with the following internet browsers: Microsoft Internet Explorer version 6 and 7, Netscape Communicator Version 4 and 5.
            </text_body>
        </req>
        <req id="OE-2">
            <text_body>
            Web Store shall operate on an Intel based system with Slackware Linux 2.6 and Apache Web Server. The operating system is designed by the Yoggie Corporation. Although maintenance documentation will be supplied and the operating system will be tested, the developers of this Web Store are not responsible for the functionality of the operating system.
            </text_body>
        </req>
        <req id="OE-3">
            <text_body>
             The system shall use SQL based database to store inventory information.
            </text_body>
        </req>
        <req id="OE-4">
            <text_body>
                USB interface and divers are provided by Yoggie Corporation.
            </text_body>
        </req>
    </p>
    <p id="2.5">
        <title>
            Design and Implementation Constraints
        </title>
        <req id="CO-1">
            <text_body>
                Must use a SQL based database. SQL standard is the most widely used database format. Restricting to SQL allows easy of use and compatibility for Web Store.
            </text_body>
        </req>
        <req id="CO-2">
            <text_body>
                Compatibility is only tested and verified for Microsoft Internet Explorer version 6 and 7, Netscape Communicator Version 4 and 5. Other versions may not be 100&#37; compatible. Also other browsers such as Mozilla or Firefox may not be 100&#37; compatible.
            </text_body>
        </req>
        
    </p>
    <p id="2.6">
        <title>
        User Documentation
        </title>
        <req id="UD-1">
            <text_body>
            Shall install online help for users via the web interface
            </text_body>
        </req>
        <req id="UD-2">
            <text_body>
            Shall deliver Operations and Maintenance manual, Users Guide book, and Installation Instructions for the Administrator.
            </text_body>
        </req>
    </p>
    <p id="2.7">
        <title>
        Assumptions and Dependencies
        </title>
        <req id="AD-1">
            <text_body>
             Assume the delivery of development, test and evaluate samples of the USB system from Yoggie.
            </text_body>
        </req>
        <req id="AD-2">
            <text_body>
            Assume Yoggie will freeze the baseline of the USB system after delivery.
            </text_body>
        </req>
    </p>
</p>

<p id="3">
    <title>
    System Features
    </title>
    <p id="3.1">
        <title>
        Customer Accounts
        </title>
        <p id="3.1.1">
